### ISSUE TITLE
HTTPS connection Insecure. 

### ISSUE THREAD

**Issue by jerryshen2017** [Whos-Hungry/dashboard-app#115]
The website connection is NOT secure. If you click on the icon right next to the URL, it says" connection to the website is insecure, usernames and password can be stolen by hackers"

**Comment by jacobfij** [comment]
Since we are using a heroku app, it is a bit complicated to actually make the interface https.  We would have to give it a wacky url and submit ourselves to some heroku issues that we would rather avoid.  HOWEVER, all api's and communication with the server are in fact secured. We talked to jesse about this to confirm that we are all good, security wise.

**Comment by jacobfij** [comment]
I'm going to leave this issue open so that people see that security s adressed.

**Comment by jerryshen2017** [comment]
Ok thanks for the feedback!

**Comment by jacobfij** [comment]
Closing this, as we are preparing the next release and any feedback at this point has been addressed.
