### ISSUE TITLE
Seaching Issues

### ISSUE THREAD

**Issue by tusharse** [Whos-Hungry/dashboard-app#126]
Firstly, as mentioned by someone the connection is not secure. You are dealing with passwords. 
Secondly, after I logged in, I am trying to search some data by entering random information, every time I click on the find recipe button: it gives me different results. Why so? you can see it in the attached image.
![14](https://user-images.githubusercontent.com/31777102/32422227-2441e460-c26d-11e7-9d93-969ae991a329.jpg)

**Comment by rachelaroberts** [comment]
Our site is secure. Please see #115. 

When clicking on "Find Recipes", it will return recipes that include the ingredients in your pantry. You can only add valid ingredients to your pantry, so nothing is in your pantry. We added a feature so that every time you click "Find Recipes" with nothing in your pantry, it just gives you random recipes. This is what it is doing to you.
Closing issue.
